"""Convert a ``topic`` :class:`TopicSpec` into a standalone skill (Phase 3-B, v0.18.0).

Provides :func:`convert_topic_to_skill` which emits a ``skill.py`` file
under ``<user-skills-dir>/<sanitised_name>/`` that replicates the
TopicSpec's regex / keyword / alias / closed-phrase / archive-after-days
behaviour as a hand-written :class:`~rin.skills.base.Skill`. The
generated skill passes :func:`~rin.skills.scaffold.validate_skill`
immediately.

Used by the "Convert to Skill" button on Settings → Topics & PoIs. The
caller is responsible for removing the original ``TopicSpec`` from
``[skills.topic]`` after the file is written.

Pure-Python, no new dependencies. The generator is deterministic — same
``TopicSpec`` always produces byte-identical output.
"""
from __future__ import annotations

import re
from pathlib import Path

from .. import paths
from .builtin.topic.skill import TopicSpec

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _sanitise(name: str) -> str:
    """Map a free-form topic name to a valid skill folder name."""
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower()
    if not cleaned:
        cleaned = "topic"
    if not cleaned[0].isalpha():
        cleaned = "t_" + cleaned
    return cleaned


def _class_name(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    return "".join(p[:1].upper() + p[1:] for p in parts if p) + "Skill"


def _format_list(items: list[str], indent: str = "    ") -> str:
    """Render a string list as a multi-line Python literal."""
    if not items:
        return "[]"
    lines = ["["]
    for item in items:
        lines.append(f"{indent}    {item!r},")
    lines.append(f"{indent}]")
    return "\n".join(lines)


def render_skill_source(topic: TopicSpec) -> str:
    """Emit the ``skill.py`` body for ``topic``.

    The returned string is what :func:`convert_topic_to_skill` writes
    to disk. Exposed separately so tests / dry-run UIs can inspect the
    generated code before any file is created.
    """
    sanitised = _sanitise(topic.name)
    cls_name = _class_name(topic.name)
    keywords = _format_list(topic.keywords)
    regex = _format_list(topic.regex)
    aliases = _format_list(topic.aliases)
    closed_phrases = _format_list(topic.closed_phrases)

    description = (
        topic.description.strip()
        or f"Auto-generated from RIN PoI {topic.name!r}"
    )
    description_safe = description.replace('"""', '\\"\\"\\"')

    return f'''\
"""Auto-generated by RIN ``Convert to Skill`` (v0.18.0).

Originally a ``topic`` PoI named {topic.name!r}.

{description_safe}

Edit freely — this file is a starting point, not a managed artefact.
RIN will not regenerate it.
"""
from __future__ import annotations

import re
from datetime import datetime, timedelta

from rin.skills.base import BucketRef, CaptureInfo, Skill, SkillContext

_NAME = {topic.name!r}
_KEY = {sanitised!r}
_KEYWORDS = {keywords}
_REGEX = {regex}
_ALIASES = {aliases}
_CLOSED_PHRASES = {closed_phrases}
_ARCHIVE_AFTER_DAYS = {topic.archive_after_days}


def _compile_safely(patterns: list[str]) -> list[re.Pattern[str]]:
    """Compile each pattern; log + skip invalid ones (matches the source
    ``topic`` engine, which tolerates bad regex by design)."""
    import logging

    log = logging.getLogger(__name__)
    out: list[re.Pattern[str]] = []
    for pattern in patterns:
        if not pattern:
            continue
        try:
            out.append(re.compile(pattern, re.IGNORECASE))
        except re.error as exc:
            log.warning(f"{{_NAME}}: skipping invalid regex {{pattern!r}}: {{exc}}")
    return out


_COMPILED_REGEX = _compile_safely(_REGEX)


class {cls_name}(Skill):
    name = {sanitised!r}
    display_name = {topic.name!r}
    version = "0.1.0"
    description = {description_safe!r}

    def detect(self, ctx: SkillContext) -> list[BucketRef]:
        haystack = "\\n".join(
            [ctx.summary or "", ctx.ocr_text or "", ctx.transcript_text or ""]
        )
        lower = haystack.lower()
        if any(pat.search(haystack) for pat in _COMPILED_REGEX):
            return [BucketRef(key=_KEY, title=_NAME)]
        for kw in _KEYWORDS + _ALIASES:
            if kw and kw.lower() in lower:
                return [BucketRef(key=_KEY, title=_NAME)]
        return []

    def should_close(
        self,
        bucket,
        captures: list[CaptureInfo],
        now: datetime,
    ) -> bool:
        if not captures:
            return False
        if _CLOSED_PHRASES:
            for cap in captures:
                text = " ".join(
                    [cap.summary or "", cap.ocr_text or "", cap.transcript_text or ""]
                ).lower()
                for phrase in _CLOSED_PHRASES:
                    if phrase and phrase.lower() in text:
                        return True
        latest = max(c.started_at for c in captures)
        return now - latest > timedelta(days=_ARCHIVE_AFTER_DAYS)


SKILL = {cls_name}()
'''


def convert_topic_to_skill(
    topic: TopicSpec,
    *,
    skills_dir: Path | None = None,
    overwrite: bool = False,
) -> Path:
    """Write a generated skill.py for ``topic`` and return its path.

    ``skills_dir`` defaults to :func:`paths.skills_dir`. Raises
    ``FileExistsError`` if the target file already exists and
    ``overwrite=False``.
    """
    base = (skills_dir or paths.skills_dir()).resolve()
    folder = base / _sanitise(topic.name)
    folder.mkdir(parents=True, exist_ok=True)
    target = folder / "skill.py"
    if target.exists() and not overwrite:
        raise FileExistsError(f"Already exists: {target}")
    target.write_text(render_skill_source(topic), encoding="utf-8")
    return target


__all__ = ["convert_topic_to_skill", "render_skill_source"]
